package pqetapp.modelpqasyapp.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 04 22:45:27 PKT 2022
// ---------------------------------------------------------------------
public interface EasyTakafulAppModule extends ApplicationModule {
    void doTMSFeedbackReasonRows();
}

