package pqetapp.modelpqasyapp.am;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import pqetapp.modelpqasyapp.am.common.EasyTakafulAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 04 22:42:17 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EasyTakafulAppModuleImpl extends ApplicationModuleImpl implements EasyTakafulAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public EasyTakafulAppModuleImpl() {
    }

    /**
     * Container's getter for VuPortalClientInfoQVORO.
     * @return VuPortalClientInfoQVORO
     */
    public ViewObjectImpl getVuPortalClientInfoQVORO() {
        return (ViewObjectImpl) findViewObject("VuPortalClientInfoQVORO");
    }

    /**
     * Container's getter for VuPortalPolicyInfoQVORO.
     * @return VuPortalPolicyInfoQVORO
     */
    public ViewObjectImpl getVuPortalPolicyInfoQVORO() {
        return (ViewObjectImpl) findViewObject("VuPortalPolicyInfoQVORO");
    }

    /**
     * Container's getter for VuPortalClaiminfoQVORO.
     * @return VuPortalClaiminfoQVORO
     */
    public ViewObjectImpl getVuPortalClaiminfoQVORO() {
        return (ViewObjectImpl) findViewObject("VuPortalClaiminfoQVORO");
    }

    /**
     * Container's getter for TmsClmWebClaimCRUD.
     * @return TmsClmWebClaimCRUD
     */
    public ViewObjectImpl getTmsClmWebClaimCRUD() {
        return (ViewObjectImpl) findViewObject("TmsClmWebClaimCRUD");
    }

    /**
     * Container's getter for VuPortalMtrPolicyDtlQVORO.
     * @return VuPortalMtrPolicyDtlQVORO
     */
    public ViewObjectImpl getVuPortalMtrPolicyDtlQVORO() {
        return (ViewObjectImpl) findViewObject("VuPortalMtrPolicyDtlQVORO");
    }

    /**
     * Container's getter for TmsClmWebComplaintCRUD.
     * @return TmsClmWebComplaintCRUD
     */
    public ViewObjectImpl getTmsClmWebComplaintCRUD() {
        return (ViewObjectImpl) findViewObject("TmsClmWebComplaintCRUD");
    }

    /**
     * Container's getter for TmsClmWebComplaintDtlCRUD.
     * @return TmsClmWebComplaintDtlCRUD
     */
    public ViewObjectImpl getTmsClmWebComplaintDtlCRUD() {
        return (ViewObjectImpl) findViewObject("TmsClmWebComplaintDtlCRUD");
    }

    /**
     * Container's getter for TmsClmWebComplaintDtlDetNextCRUD.
     * @return TmsClmWebComplaintDtlDetNextCRUD
     */
    public ViewObjectImpl getTmsClmWebComplaintDtlDetNextCRUD() {
        return (ViewObjectImpl) findViewObject("TmsClmWebComplaintDtlDetNextCRUD");
    }

    /**
     * Container's getter for TMSComplaintComplaintReasonComplaintIdPkLink1.
     * @return TMSComplaintComplaintReasonComplaintIdPkLink1
     */
    public ViewLinkImpl getTMSComplaintComplaintReasonComplaintIdPkLink1() {
        return (ViewLinkImpl) findViewLink("TMSComplaintComplaintReasonComplaintIdPkLink1");
    }

    /**
     * Container's getter for TMSComplaintComplaintReasonComplaintIdPkLink2.
     * @return TMSComplaintComplaintReasonComplaintIdPkLink2
     */
    public ViewLinkImpl getTMSComplaintComplaintReasonComplaintIdPkLink2() {
        return (ViewLinkImpl) findViewLink("TMSComplaintComplaintReasonComplaintIdPkLink2");
    }
    public void doTMSFeedbackReasonRows() {
            getTmsClmStFeedbackViewRO().executeQuery();
            getTmsClmStFeedbackViewRO().setRangeSize(-1);
            for (int i = 0; i < getTmsClmStFeedbackViewRO().getRowCount(); i++) {
                System.out.println("printing"+i);
                Row r=getTmsClmWebFeedbackCRUD().createRow();
                r.setAttribute("FeedbackIdPk", getTmsClmStFeedbackViewRO().getRowAtRangeIndex(i).getAttribute("FeedbackIdPk"));
                getTmsClmWebFeedbackCRUD().insertRow(r);
           }

    }

    /**
     * Container's getter for TmsClmStFeedbackView1.
     * @return TmsClmStFeedbackView1
     */
    public ViewObjectImpl getTmsClmStFeedbackViewRO() {
        return (ViewObjectImpl) findViewObject("TmsClmStFeedbackViewRO");
    }

    /**
     * Container's getter for TmsClmWebFeedbackView1.
     * @return TmsClmWebFeedbackView1
     */
    public ViewObjectImpl getTmsClmWebFeedbackCRUD() {
        return (ViewObjectImpl) findViewObject("TmsClmWebFeedbackCRUD");
    }
}

