package pqetapp.modelpqasyapp.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 03 23:37:00 PKT 2022
// ---------------------------------------------------------------------
public interface TmsClmWebComplaintViewRow extends Row {
    void doTMSInsertReasonRows();
}

